'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated from a template.
'
'     Manual changes to this file may cause unexpected behavior in your application.
'     Manual changes to this file will be overwritten if the code is regenerated.
' </auto-generated>
'------------------------------------------------------------------------------

Imports System
Imports System.Data.Entity
Imports System.Data.Entity.Infrastructure

Partial Public Class InventariosEntities
    Inherits DbContext

    Public Sub New()
        MyBase.New("name=InventariosEntities")
    End Sub

    Protected Overrides Sub OnModelCreating(modelBuilder As DbModelBuilder)
        Throw New UnintentionalCodeFirstException()
    End Sub

    Public Overridable Property Empresas() As DbSet(Of Empresas)
    Public Overridable Property EmpresasParaUsuarios() As DbSet(Of EmpresasParaUsuarios)
    Public Overridable Property Modulos() As DbSet(Of Modulos)
    Public Overridable Property Permisos() As DbSet(Of Permisos)
    Public Overridable Property PermisosParaRoles() As DbSet(Of PermisosParaRoles)
    Public Overridable Property Roles() As DbSet(Of Roles)
    Public Overridable Property sysdiagrams() As DbSet(Of sysdiagrams)
    Public Overridable Property Usuarios() As DbSet(Of Usuarios)
    Public Overridable Property UsuariosParaRoles() As DbSet(Of UsuariosParaRoles)

End Class
