'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated from a template.
'
'     Manual changes to this file may cause unexpected behavior in your application.
'     Manual changes to this file will be overwritten if the code is regenerated.
' </auto-generated>
'------------------------------------------------------------------------------

Imports System
Imports System.Collections.Generic

Partial Public Class Roles
    Public Property GUIDRol As System.Guid
    Public Property Nombre As String
    Public Property Observaciones As String
    Public Property Activo As Boolean
    Public Property GUIDUsuarioAlta As System.Guid
    Public Property FechaAlta As Date
    Public Property GUIDUsuarioCambio As System.Guid
    Public Property FechaCambio As Date

    Public Overridable Property PermisosParaRoles As ICollection(Of PermisosParaRoles) = New HashSet(Of PermisosParaRoles)
    Public Overridable Property UsuariosParaRoles As ICollection(Of UsuariosParaRoles) = New HashSet(Of UsuariosParaRoles)

End Class
