'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated from a template.
'
'     Manual changes to this file may cause unexpected behavior in your application.
'     Manual changes to this file will be overwritten if the code is regenerated.
' </auto-generated>
'------------------------------------------------------------------------------

Imports System
Imports System.Collections.Generic

Partial Public Class EmpresasParaUsuarios
    Public Property GUIDEmpresaParaUsuario As System.Guid
    Public Property GUIDEmpresa As System.Guid
    Public Property GUIDUsuario As System.Guid
    Public Property Activo As Boolean
    Public Property GUIDUsuarioAlta As System.Guid
    Public Property FechaAlta As Date
    Public Property GUIDUsuarioCambio As System.Guid
    Public Property FechaCambio As Date

    Public Overridable Property Empresas As Empresas
    Public Overridable Property Usuarios As Usuarios

End Class
