'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated from a template.
'
'     Manual changes to this file may cause unexpected behavior in your application.
'     Manual changes to this file will be overwritten if the code is regenerated.
' </auto-generated>
'------------------------------------------------------------------------------

Imports System
Imports System.Collections.Generic

Partial Public Class Permisos
    Public Property GUIDPermiso As System.Guid
    Public Property Nombre As String
    Public Property Descripcion As String
    Public Property GUIDModulo As System.Guid
    Public Property Activo As Boolean
    Public Property GUIDUsuarioAlta As System.Guid
    Public Property FechaAlta As Date
    Public Property GUIDUsuarioCambio As System.Guid
    Public Property FechaCambio As Date

    Public Overridable Property Modulos As Modulos
    Public Overridable Property PermisosParaRoles As ICollection(Of PermisosParaRoles) = New HashSet(Of PermisosParaRoles)

End Class
